---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  labels:
    app: crawler
    component: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler
  template:
    metadata:
      name: crawler
      labels:
        app: crawler
        component: crawler
    spec:
      containers:
      - image: vdaishi/crawler:1.0
        name: app
        env:
        - name: MONGO
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"
        - name: RMQ_HOST
          value: "rabbit-service"
        - name: RMQ_USERNAME
          value: "guest"
        - name: RMQ_PASSWORD
          value: "guest"
        - name: CHECK_INTERVAL
          value: "10"
        - name: EXCLUDE_URLS
          value: ".*github.com"
